### ISSUE TITLE
Carrier Shipment Method Management

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment-pwa#493]
## What is the motivation for adding/enhancing this feature?

Figma link: https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34101-119419&mode=design&t=yjAE31llpwfSiHhN-11

Doc link: https://github.com/hotwax/oms-documentation/blob/user-guides-pub/user-manuals/fulfillment/carrier-and-shipment-methods.md

**Comment by ravilodhi** [comment]
Dependant on following changes in OMS -

1) https://git.hotwax.co/commerce/oms/-/merge_requests/4753 - Merged on May 8, 2024 
2) https://git.hotwax.co/commerce/oms/-/merge_requests/4742 - Merged on May 7, 2024

**Comment by Adameddy26** [comment]
There are few more issues which I have found  - 

1. If 'only methods for this carrier' toggle is set to ON, then it does not change on creation of new carrier or switching between carriers. Ideally it should get set back to OFF in both the situations.
2. When changes are applied for the carrier code or delivery days, then the methods name are getting disappeared from the UI.(Check in product store section)
3. Last line appearing in the popover of method card can be removed.
4. Method or carrier name can be edited and saved with no change. Same for carrier code and delivery days. User is able to type and save the carrier/delivery days field using special characters/characters/space.
5. Sequencing of methods is not working. Sequencing modal should not be open in case one selected method. Also modal save button should appear disabled on open because of no change. Also on trying to setup the same sequence as of earlier, save button should appear disabled.

**Comment by Adameddy26** [comment]
Considering the above raised issues, reopening this ticket for now.

**Comment by Adameddy26** [comment]
1. Method or carrier name can be saved with blank space.
2. On trying to save the delivery days/carrier code/gateway with no value, there should not be any toast message generated.
3. If negative values are entered in delivery days/carrier code and user tries to save it, then in this case the toast message should be modified.
4. When user tries to create a method whose ID already exists, then in this case toast message should be modified.
5. Popover should get closed on selecting any option from it.
6. 'Only methods for this carrier' toggle should be OFF when user finishes the carrier setup.
7. Long method name is overlapping with the delivery days chip.
8. Scroll position is not retaining its top position in case user opens a carrier > navigates to some other section of App > Go back to carrier shipment method section.

**Comment by ravilodhi** [comment]
#1 Fixed
#2 Fxied
#3 Fixed
#4 Fixed
#5 Fixed
#6 Fixed
#7, #8 Create a sperate ticket with low priority.

**Comment by Adameddy26** [comment]
Verified all the fixes and are working fine in release v2.4.3. Hence ,closing this ticket.

**Comment by Adameddy26** [comment]
https://github.com/hotwax/fulfillment/pull/567
Verified the above pull request changes in release v2.5.0 and found that they are working fine.
![Screenshot from 2024-06-24 10-22-31](https://github.com/hotwax/fulfillment/assets/158989293/9f85eaaf-f8ae-4f95-b80c-11518021eaed)

**Comment by Adameddy26** [comment]
Verified the https://github.com/hotwax/fulfillment/pull/568 pull request changes and are working fine in release v2.5.0. 
![Screenshot from 2024-06-24 10-36-06](https://github.com/hotwax/fulfillment/assets/158989293/bab847ac-d3df-4715-ab22-1020e986d69e)
